export interface KitsuData {
    // $schema:    string;
    type:       string;
    properties: KitsuAnimeDataProperties;
    required:   string[];
}

export interface KitsuAnimeDataProperties {
    data:  Data;
    meta:  Meta;
    links: Links;
}

export interface Data {
    type: string;
}

export interface Links {
    type:       string;
    properties: LinksProperties;
}

export interface LinksProperties {
    first: Data;
    prev:  Data;
    next:  Data;
    last:  Data;
}

export interface Meta {
    type:       string;
    properties: MetaProperties;
    required:   string[];
}

export interface MetaProperties {
    count: Data;
}

// Generated by https://quicktype.io

export interface JikanData {
    data: Data[];
}

export interface Data {
    mal_id:           number;
    url:              string;
    images:           { [key: string]: Image };
    trailer?:         Trailer;
    approved:         boolean;
    titles:           Title[];
    title:            string;
    title_english:    string;
    title_japanese:   string;
    title_synonyms?:  string[];
    type:             string;
    source?:          string;
    episodes?:        number;
    chapters?:        number;
    volumes?:         number;
    status:           string;
    airing?:          boolean;
    aired?:           Aired;
    publishing?:      boolean;
    published?:       Published;
    duration:         string;
    rating?:          string;
    score:            number;
    scored_by:        number;
    rank:             number;
    popularity:       number;
    members:          number;
    favorites:        number;
    synopsis:         string;
    background:       string;
    season?:          string;
    year?:            number;
    broadcast?:       Broadcast;
    producers?:       Demographic[];
    licensors?:       Demographic[];
    studios?:         Demographic[];
    authors:          Author[];
    serializations:   Author[];
    genres:           Demographic[];
    explicit_genres:  Demographic[];
    themes:           Demographic[];
    demographics:     Demographic[];
}

export interface Author {
    mal_id: number;
    type:   string;
    name:   string;
    url:    string;
}

export interface Aired {
    from: string;
    to:   string;
    prop: Prop;
}

export interface Published {
    from: string;
    to:   string;
    prop: Prop;
}

export interface Prop {
    from:   From;
    to:     From;
    string: string;
}

export interface From {
    day:   number;
    month: number;
    year:  number;
}

export interface Broadcast {
    day:      string;
    time:     string;
    timezone: string;
    string:   string;
}

export interface Demographic {
    mal_id: number;
    type:   string;
    name:   string;
    url:    string;
}

export interface Image {
    image_url:       string;
    small_image_url: string;
    large_image_url: string;
}

export interface Title {
    type:  string;
    title: string;
}

export interface Trailer {
    youtube_id: string;
    url:        string;
    embed_url:  string;
}
